version: '3'
services:
  frontend:
    build: .
    env_file: client/src/app.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd client && yarn start'
    ports:
      - 8000:3000
    tty: true
